### PR TITLE
Code fixes to pass lint requirements

### PR DESCRIPTION
**Pull request by gfechio**
This needs to be merged after having the Pylint action in place. Basically adding some pipeline here to allow the continuity of the project.

### CODE REVIEW

**Comment by milcent** [comment]
Now, this will take some time...
I have started in benford.py file.
Can you help with the others??
Thanks in advance

**Comment by milcent** [comment]
I got it!
With autopep8 and some changes in the dependencies installations during builds.
Thanks again

**Comment by milcent** [comment]
Come to think of it, wouldn't it be batter to set the branch for all these tests to be the `develop` one?
So, when everything is allright in the `develop`, it can be merged to master.

**Comment by gfechio** [comment]
> Come to think of it, wouldn't it be batter to set the branch for all these tests to be the `develop` one?
> So, when everything is allright in the `develop`, it can be merged to master.

Yes , in the best case scenario you would never commit to master and would have either a 'development' branch or versioned branch with push request to build the package with versioning. But for free accounts in GitHub you can't protect master, so you can't actually enforce it. Summing up: better have a `develop` branch anyway.

**Pull request merged**
